version: '3'       # 1
services:          # 2
  db:
    image: mysql:8.0

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: django
      MYSQL_USER: django
      MYSQL_PASSWORD: django
      TZ: 'Asia/Tokyo'

    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000 # 7
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db